name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: setup 7-zip
      uses: milliewalky/actions/setup-7-zip@v2

    - name: checkout @ master
      uses: actions/checkout@v4
      with:
        ref: master

    - name: check cwd
      shell: cmd
      run: |
        echo %cd%
        dir %cd%
        dir %cd%\..

    - name: get sha
      id: sha_from_git
      shell: cmd
      run: |
        for /f %%a in ('git rev-parse --short HEAD') do set v=%%a
        echo sha_value=%v%>> %GITHUB_OUTPUT%

    - name: get branch
      id: branch_from_git
      shell: cmd
      run: |
        for /f %%a in ('git rev-parse --abbrev-ref HEAD') do set v=%%a
        echo branch_value=%v%>> %GITHUB_OUTPUT%

    - name: build debug
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        call build.bat sample msvc debug || exit /b 1

    - name: build -> debug, mkdir build and move
      shell: cmd
      run: |
        ren build debug
        mkdir build
        move debug build

    - name: build release
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        call build.bat sample msvc release || exit /b 1

    - name: tidy up build dir
      shell: cmd
      run: for /r build %%a in (*) do if /I "%%~xa" neq ".exe" if /I "%%~xa" neq ".pdb" del "%%a"

    - name: pack artifacts into an archive and push to gh
      uses: actions/upload-artifact@v4
      with:
        name: sample-windows-x86_64-${{ steps.branch_from_git.outputs.branch_value }}-${{ steps.sha_from_git.outputs.sha_value }}
        path: .\build\
        compression-level: 9
