name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout @ master
      uses: actions/checkout@v4
      with:
        ref: master

    - name: get sha
      id: sha_from_git
      shell: cmd
      run: |
        for /f %%i in ('git rev-parse --short HEAD') do set v=%%i
        echo sha_value=%v%>> %GITHUB_OUTPUT%

    - name: get branch
      id: branch_from_git
      shell: cmd
      run: |
        for /f %%i in ('git rev-parse --abbrev-ref HEAD') do set v=%%i
        echo branch_value=%v%>> %GITHUB_OUTPUT%

    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        call build.bat sample || exit /b 1

    - name: pack artifact into an archive and push to gh
      uses: actions/upload-artifact@v4
      with:
        name: sample-windows-x86_64-${{ steps.branch_from_git.outputs.branch_value }}-${{ steps.sha_from_git.outputs.sha_value }}
        path: .\build\
        compression-level: 9
